/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/v1/translate": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Translate input into a structured output */
		post: operations["postApiV1Translate"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/health": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Health check */
		get: operations["getApiHealth"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: never;
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	postApiV1Translate: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": {
					input: string;
					model: string;
					/** @enum {string} */
					target: "vcs-commit-message" | "pr-title-body" | "pr-intent";
				};
				"application/x-www-form-urlencoded": {
					input: string;
					model: string;
					/** @enum {string} */
					target: "vcs-commit-message" | "pr-title-body" | "pr-intent";
				};
				"multipart/form-data": {
					input: string;
					model: string;
					/** @enum {string} */
					target: "vcs-commit-message" | "pr-title-body" | "pr-intent";
				};
			};
		};
		responses: {
			/** @description Response for status 200 */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						output: string;
						content: string;
						vendor: string;
						model: string;
						inputTokens: number;
						outputTokens: number;
						cachedInputTokens?: number;
						cost?: number;
						generationId?: string;
					};
				};
			};
			/** @description Response for status 400 */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						error: string;
					};
				};
			};
			/** @description Response for status 401 */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						error: string;
					};
				};
			};
			/** @description Response for status 402 */
			402: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						/** @constant */
						error: "insufficient_balance";
						message: string;
						balance: number;
						/** @enum {string} */
						plan: "free" | "pro";
						actions: {
							buyCredits?: string;
							enableAutoRecharge?: string;
							upgrade?: string;
						};
						hint: string;
					};
				};
			};
		};
	};
	getApiHealth: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Response for status 200 */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						status: string;
					};
				};
			};
		};
	};
}
